services:
  one_marketplace_marketing_service:
    build:
      dockerfile: Dockerfile
      context: .
    image: one-marketplace-marketing-service:latest
    container_name: one_marketplace_marketing_service
    restart: unless-stopped
    depends_on:
      - one_marketplace_marketing_service_db
    stdin_open: true
    tty: true
    working_dir: /usr/src/one_marketplace_marketing_service
    volumes:
      - ./:/usr/src/one_marketplace_marketing_service
    ports:
      - "5003:5003"
      - "7003:7003"
    networks:
    - one_marketplace_network

  one_marketplace_marketing_service_db:
    image: postgres:16-alpine
    container_name: one_marketplace_marketing_service_db
    environment:
      POSTGRES_USER: ${OMMARKETINGDBUSER}
      POSTGRES_PASSWORD: ${OMMARKETINGDBPASSWORD}
      POSTGRES_DB: ${OMMARKETINGDB}
    ports:
      - 5403:5432
    networks:
      - one_marketplace_network

networks:
  one_marketplace_network:
    external: true
