services:
  one_marketplace_user_service:
    build:
      dockerfile: Dockerfile
      context: .
    image: one-marketplace-user-service:latest
    container_name: one_marketplace_user_service
    restart: unless-stopped
    depends_on:
      - one_marketplace_user_service_db
    stdin_open: true
    tty: true
    working_dir: /usr/src/one_marketplace_user_service
    volumes:
      - ./:/usr/src/one_marketplace_user_service
    ports:
      - "5010:5010"
      - "7010:7010"
    networks:
    - one_marketplace_network

  one_marketplace_user_service_db:
    image: postgres:16-alpine
    container_name: one_marketplace_user_service_db
    environment:
      POSTGRES_USER: ${OMUSERDBUSER}
      POSTGRES_PASSWORD: ${OMUSERDBPASSWORD}
      POSTGRES_DB: ${OMUSERDB}
    ports:
      - 5410:5432
    networks:
      - one_marketplace_network

networks:
  one_marketplace_network:
    external: true
